"""Initial migration.

Revision ID: 9ea3b487680c
Revises: 
Create Date: 2024-07-31 15:05:06.537589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea3b487680c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('occasion', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.String(length=80), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('accomodation', sa.String(length=120), nullable=True),
    sa.Column('special', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org')
    # ### end Alembic commands ###
