"""update organize_id

Revision ID: a55ae16e9353
Revises: 2c56397b0e06
Create Date: 2024-08-06 20:16:13.400305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55ae16e9353'
down_revision = '2c56397b0e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('organizer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('organizer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
